### ISSUE TITLE
A11y: Announce the change of context when navigating from one page to another

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#340] opened 2024-02-12 20:00 UTC
## Description

When a screen reader user navigates to a page in the pagination, they currently don't get any context that, say, page 2 has loaded and have no context where the change took place on the page. We should give them an announcement that new content has loaded. This could be achieved by using an `aria-live` region.

## Recommendation:

- [ ] When the page updates, we could announce "property list updated, page 2"  to give users a hint that the property list has been updated.

Touches the following WCAG Criteria:

[4.1.2 Name, Role, Value Level A](https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html)
[4.1.3 Status Messages Level AA](https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html)

**Comment by bacitracin** [comment] 2024-07-02 17:13
I think this is a dupe of https://github.com/CodeForPhilly/clean-and-green-philly/issues/657#issue-2319071940 so closing

**Closed by bacitracin** 2024-07-02 17:13 UTC
Labels: A11y
