### ISSUE TITLE
Filter list boxes: Users lose context on the option after selecting it

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#651] opened 2024-05-27 09:49 UTC
## Description
Tracy Note: This ticket is related to https://github.com/CodeForPhilly/clean-and-green-philly/issues/631 & probably would be fixed with that refactor to pull out the selected pills from the dropdown.

When selecting an option in the listbox "Neighborhoods" , "Community Organizations" or "Zoning", we remove the option from the list, and put it in a pill form. When a screen reader user selects this option, we do not give feedback about what happened to the option after selecting it. It just disappears in the list. This can potentially throw off screen reader users and would require them extra steps to investigate to what had happened with their selection.

<details>
<summary>DEMO: NVDA+FF. For this ticket, see 0:00-1:40  part of the demo</summary>

https://github.com/CodeForPhilly/clean-and-green-philly/assets/102739972/ade5b3b2-ca41-4165-ac9f-6bbbb8ca462c

</details>

## Recommendation
- Option 1: Keep them in the list, put a checkmark to visually distinguish that it's been selected. Announce the selected state.  Deselecting this would clear the pill. This would be the cleanest experience. 
- Option 2: Have a mechanism to announce that the option has been selected and removed from the list.

**Comment by zheyichn** [comment] 2024-07-02 15:28
Hi, may I be assigned this ticket?

**Comment by bacitracin** [comment] 2024-07-02 15:47
@zheyichn assigned!

**Comment by zheyichn** [comment] 2024-07-02 16:51
Hi @bacitracin @marvieqa 

I have one question. At 1:40 in the video above, what are the proper key(s) used to exit the dropdown list? I pressed `Esc` to leave the dropdown menu, but the selected items disappeared, leaving only one empty pill form as shown below. This issue persists whether or not I make any changes.

<img width="1312" alt="exit-dropdown" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/88219993/658d9467-a2ce-448c-9027-dbb3604f9fdf">

**Comment by bacitracin** [comment] 2024-07-02 16:54
@zheyichn I don't have time to check on this right now, but this ticket is related to the bug you mentioned and calls out expected behavior https://github.com/CodeForPhilly/clean-and-green-philly/issues/631#issue-2296592210

**Comment by bacitracin** [comment] 2024-07-02 16:59
Hey @zheyichn, if you haven't gotten too deep in this, I'd like to take this ticket back and work on it some more. It turns out that we have 5 other filter related tickets created, and I want to make sure they are all aligned in behavior before people start working on them.

**Comment by zheyichn** [comment] 2024-07-02 17:11
Hey @bacitracin So far, I have made only a few changes to implement option 1 as stated above. I believe the issue with exiting the dropdown is out of the scope of this task. That sounds good—I'll hold off on further work for now. Let me know when it's ready. Thanks!

**Comment by bacitracin** [comment] 2024-07-02 17:15
@zheyichn Cool, sorry for the confusion! I've put "Blocked" on all the tickets in review so it shouldn't happen again. I'll keep in mind that option 1 was doable/we have work done already.

**Comment by nlebovits** [comment] 2024-09-25 00:21
@bacitracin where does this issue stand? should we rewrite and reissue, keep it as is, or close as unplanned?

**Comment by bacitracin** [comment] 2024-09-27 02:23
@nlebovits This one would be likely be fixed by the refactor suggested in https://github.com/CodeForPhilly/clean-and-green-philly/issues/631. I'll close this so people don't work on it on its own., it's a bit of a dupe ticket.

**Comment by bacitracin** [comment] 2024-09-27 02:23
Closing since this issue will be tackled in a different ticket.

**Closed by bacitracin** 2024-09-27 02:23 UTC
Labels: A11y
