### ISSUE TITLE
Task: Audit performance of homepage

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#733] opened 2024-07-08 22:18 UTC
## Describe the task

Audit performance of Clean and Green Philly's [homepage](https://www.cleanandgreenphilly.org/) using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [x] Generate Lighthouse report for mobile devices
- [x] Generate Lighthouse report for desktop devices
- [x] Post screenshots of results in this issue's comments section
- [x] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by CodeWritingCow** [comment] 2024-07-09 03:13
## Lighthouse report for mobile devices

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/6565782a-7a42-4069-ae8e-5247c383d17a)
![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/fd364642-d262-442a-bdd5-5d36732cb090)
![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/07f78413-0801-4b79-a374-a1816148546c)

**Comment by CodeWritingCow** [comment] 2024-07-09 03:24
## Lighthouse report for desktop devices

Performance score was 61/100. Score took a hit due to the page's blocking time of 2.26 seconds.

## Screenshots

![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/61d4bf82-9790-409f-8843-b8a152d436af)
![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/3e81ff4e-f310-43a1-83d0-c2f95219c3ba)
![Image](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/c22ac783-8844-4401-b092-ba60cba548fc)

**Comment by CodeWritingCow** [comment] 2024-07-21 17:19
Unassigned myself from this issue so other contributors can work on it. I've posted screenshots of the audit reports. Only things missing are report summaries and recommendations for improvement.

**Comment by zheyichn** [comment] 2024-07-21 20:20
Hi @CodeWritingCow, can I be assigned this pls?

**Comment by CodeWritingCow** [comment] 2024-07-21 20:23
@zheyichn assigned! Thank you for taking this off my plate.

**Comment by zheyichn** [comment] 2024-07-21 21:33
When I ran the Lighthouse report in my local incognito window, it displayed different results from the above screenshots. According to the screenshots above, the high total blocking time mainly penalized the performance score. However, I did not see total blocking time as a problem on my end. To provide improvement recommendations, I need to click in to see detailed information. Therefore, I have posted my screenshots below and will summarize based on these.

## Lighthouse report for desktop devices
- Performance score was 99/100, no blocking time detected.
- Accessibility score was 92/100, due to misuse of `aria-*` attribute on `nav` element.

## Screenshots
<img width="569" alt="home-desktop-1" src="https://github.com/user-attachments/assets/5fbc602a-d9cd-49f1-9c4a-347b71071c46">

<img width="569" alt="home-desktop-2" src="https://github.com/user-attachments/assets/1747d616-eac2-4529-b413-a916e06f1ad0">

<img width="569" alt="home-desktop-3" src="https://github.com/user-attachments/assets/51bd5ed7-eb92-4cc6-b0c0-29b4202f55b2">

<img width="569" alt="home-desktop-4" src="https://github.com/user-attachments/assets/b1f01dc6-6e20-4b4c-b30e-f0ac29f67502">

<img width="569" alt="home-desktop-5" src="https://github.com/user-attachments/assets/47c0c4fd-a43a-4be0-8876-45ee8085c165">

<img width="569" alt="home-desktop-6" src="https://github.com/user-attachments/assets/b8caf042-94ab-4f2c-adc5-2a7cd81567f9">

**Comment by zheyichn** [comment] 2024-07-21 22:15
## Lighthouse report for mobile devices
- Performance score was 75/100, penalized due to the `Largest Contentful Paint` taking 6.45 seconds.

## Screenshots

<img width="569" alt="home-mobile-1" src="https://github.com/user-attachments/assets/75cb3d72-6781-4d25-bd37-b30275c4872e">

<img width="569" alt="home-mobile-2" src="https://github.com/user-attachments/assets/ff591628-bc1d-446f-86d5-49e793f8d200">

<img width="569" alt="home-mobile-3" src="https://github.com/user-attachments/assets/e9b0ff55-9401-48e8-bbe3-57e5f2d09271">

<img width="569" alt="home-mobile-4" src="https://github.com/user-attachments/assets/6ac4f741-c211-4fae-93e5-02ea7cee8dbe">

<img width="569" alt="home-mobile-5" src="https://github.com/user-attachments/assets/2e4b7742-f791-45f4-a49a-eb962032e6c7">

<img width="569" alt="home-mobile-6" src="https://github.com/user-attachments/assets/6c71fa09-0383-45e2-86a6-84f771af75d5">

<img width="569" alt="home-mobile-7" src="https://github.com/user-attachments/assets/8ef03866-9fe9-4ad6-90f4-a52ede9963ad">

**Comment by zheyichn** [comment] 2024-07-21 22:38
## Summary of audit highlights.
- Scores were good on desktop devices.
- Performance score was 75/100 on mobile devices due to `Largest Contentful Paint` taking 6 seconds.

## Improvement suggestions.
1. Investigate the cause of the image `Load delay` (59% of LCP) - The delta between `Time to first byte` and when the browser starts loading the LCP resource. (Performance)
2. Remove unused CSS - Splitting the `global.css` file into smaller files specific to different pages/components can help avoid loading unnecessary CSS. (Performance)
3. `aria-pressed` cannot be used on `nav` element. Relevant to #727.

**Comment by CodeWritingCow** [comment] 2024-07-24 02:11
@zheyichn thanks for digging into this. It seems image load delay and unused CSs are common issues on the website.

**Closed** 2024-07-30 23:19 UTC
Labels: good first issue, frontend
