### ISSUE TITLE
Task: Audit performance of Accessibility Statement page

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/clean-and-green-philly#740] opened 2024-07-09 03:35 UTC
## Describe the task

Audit performance of Clean and Green Philly's [Accessibility Statement](https://www.cleanandgreenphilly.org/accessibility-statement) page using Google Lighthouse. Document audit results, including areas of improvement.

## Acceptance Criteria

- [x] Generate Lighthouse report for mobile devices
- [x] Generate Lighthouse report for desktop devices
- [x] Post screenshots of results in this issue's comments section
- [x] Write brief summary of audit highlights, including Lighthouse's recommendations for improvement

## Additional context

* For instructions on using Lighthouse, see https://developer.chrome.com/docs/lighthouse/overview

**Comment by bacitracin** [comment] 2024-07-11 16:39
@zheyichn assigned!

**Comment by zheyichn** [comment] 2024-07-11 20:20
## Lighthouse report for mobile devices
- Performance score was 74/100, affected by Largest Contentful Paint of 6.3 seconds.
- Accessibilty score was 95/100. The penalty came from `aria-*` attribute does not match their roles, which is mentioned in #727 too.
- SEO score was 91/100 due to links on page are not crawlable.
 
### Screenshoots
![a11y-mobile-1](https://github.com/user-attachments/assets/e55a5d7f-b352-4df2-b25f-c735ce6b8f88)

![a11y-mobile-2](https://github.com/user-attachments/assets/43f3685d-6673-4ab6-b1e8-f44fee131613)

![a11y-mobile-3](https://github.com/user-attachments/assets/a9e969fc-5def-472c-ab62-583d045f4b35)

![a11y-mobile-4](https://github.com/user-attachments/assets/095b6f6d-a69b-4a57-99cd-3db0a1c8530c)

![a11-mobile-5](https://github.com/user-attachments/assets/13f4e501-1bee-4680-8a3e-ce4d8a6844b0)

**Comment by zheyichn** [comment] 2024-07-11 20:37
## Lighthouse report for desktop devices
- Performance score was 97/100, affected by Largest Contentful Paint of 1.2 seconds.
- Accessiblity score was 95/100 because mismatch of `aria-*` attribute and their roles, which is also mentioned #727.
- SEO score was 91/100, as links are not crawlable.

### Screenshots
![a11y-desk-1](https://github.com/user-attachments/assets/2cf2fb4b-b6d9-4fba-b121-b59100cc88ad)

![a11y-desk-2](https://github.com/user-attachments/assets/5ff54b03-ce9b-4b48-95dc-d0f554d51a34)

![a11y-desk-3](https://github.com/user-attachments/assets/39eacb87-6a6a-48ca-8863-b5a1ffdd2cd0)

![a11y-desk-4](https://github.com/user-attachments/assets/82f7ec38-5c42-4677-854a-80063927b248)

![a11y-desk-5](https://github.com/user-attachments/assets/0704e633-686a-46f6-8a72-056e79f099ec)

**Comment by zheyichn** [comment] 2024-07-11 20:50
## Summary
- Performance gets penalty from long image loading time.
- Accessiblity is good (95/100) on both devices. Points deducted from misue of `aria-*` attribute on <nav> elements. This issue has been reported in #727 previously But currently wontfix since it came from NextUI.
- SEO requires links to be crawlable.

## Improvement recommendations
### For both mobile devices & desktop devices

1. Explore how to reduce image loading time. (Performance)
2. Resolve the aria-* mismatch with role issue of the menu button, possibily by refactoring the menu component as discussed in #727. (Accessibility)
3.  Make links crawlable to search engines. (SEO)

**Comment by CodeWritingCow** [comment] 2024-07-11 21:55
@zheyichn thanks for digging into this. This page has room for improvement on mobile devices. Based on your recommendations, I will create an issue for exploring how to reduce image loading time on this page.

Our SEO score is good on this page (low 90s). For now, let's prioritize improving page load time because that will benefit our site users more.

**Comment by CodeWritingCow** [comment] 2024-07-15 05:33
@zheyichn I noticed these two recommendations from Lighthouse: "Reduce unused JavaScript" and "Reduce unused CSS." Did the Lighthouse report have details on what JS and CSS can be removed?

**Comment by zheyichn** [comment] 2024-07-15 19:22
Hi @CodeWritingCow , the report didn't directly point out unused code. I tried navigating to the `Coverage` tab, and it semed to display some compiled CSS/JS code. Do you know how I can trace back to lines of code in our codebase?

<img width="493" alt="unused_javascript" src="https://github.com/user-attachments/assets/791f31ef-903f-430a-933e-e34068febc00">

<img width="1042" alt="unused-css" src="https://github.com/user-attachments/assets/376f436f-d7c8-4458-98e7-f40ac752000c">

**Comment by zheyichn** [comment] 2024-07-15 19:55
Additionally, I looked into how to reduce logo image loading time. The delay mostly came from `render delay`, meaning rendering is blocked after image resource was loaded.
I found some suggestions on how to improve this, which require cleaning CSS and JS code, or splitting CSS code into smaller files.

- https://web.dev/articles/optimize-lcp
- https://developer.chrome.com/docs/lighthouse/performance/render-blocking-resources#how_to_eliminate_render-blocking_scripts

<img width="656" alt="render-delat" src="https://github.com/user-attachments/assets/d63f0836-b535-40b0-86ef-b1a6fd6d80a2">

![image](https://github.com/user-attachments/assets/4fc1968d-cd80-4648-9a3a-01728117f24d)

To ensure the `render delay` was caused by large stylesheets, I ran Lighthouse on locally served a11y page with `global.css` removed. And it indeed stopped complaining about `LCP` as the screenshoot below shows. @CodeWritingCow  Do you think this is the right direction to work towards - clean up CSS/JS code? I'm still trying to figure out how to identify unused code blocks for each page precisely. Thanks.

<img width="656" alt="css-removed-LCP" src="https://github.com/user-attachments/assets/e5281a40-0864-4a56-bbd9-c86d16c1937b">

**Comment by CodeWritingCow** [comment] 2024-07-16 04:06
Hi @zheyichn, generally we would use source maps during development to trace compiled code back to the original code. However, Next.js apps disable source maps in production by default.

As a workaround, try running Lighthouse in localhost. The Coverage tab should show uncompiled CSS/JavaScript code.

I like your ideas of cleaning up unused CSS/JS code, and splitting some CSS into smaller files. Definitely worth exploring further. For example, `globals.css` has many styling rules for `maplibregl`, but only the Find Properties page needs those rules. Other pages shouldn't have to load those rules.

**Closed** 2024-09-25 00:59 UTC
Labels: good first issue, frontend
